### ISSUE TITLE
Error while building for PHP-7.3.1

### ISSUE THREAD

**Issue by kasuganosoras** [pierrejoye/php_zip#23] opened 2019-01-30 02:58 UTC
When I run the command `make`

```
/bin/sh /tmp/pear/temp/pear-build-rootSH6myv/zip-1.15.4/libtool --mode=compile cc -I/usr/local/include -I. -I/tmp/pear/temp/zip -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootSH6myv/zip-1.15.4/include -I/tmp/pear/temp/pear-build-rootSH6myv/zip-1.15.4/main -I/tmp/pear/temp/zip -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/tmp/pear/temp/zip/php73  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/zip/php73/php_zip.c -o php73/php_zip.lo
mkdir php73/.libs
 cc -I/usr/local/include -I. -I/tmp/pear/temp/zip -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootSH6myv/zip-1.15.4/include -I/tmp/pear/temp/pear-build-rootSH6myv/zip-1.15.4/main -I/tmp/pear/temp/zip -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/tmp/pear/temp/zip/php73 -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/zip/php73/php_zip.c  -fPIC -DPIC -o php73/.libs/php_zip.o
In file included from /usr/local/include/zip.h:45:0,
                 from /tmp/pear/temp/zip/php73/php_zip.h:31,
                 from /tmp/pear/temp/zip/php73/php_zip.c:36:
/tmp/pear/temp/zip/php73/php_zip.c: In function 'php_zip_object_free_storage':
/tmp/pear/temp/zip/php73/php_zip.c:1032:63: error: invalid suffix "a" on integer constant
 #if LIBZIP_VERSION_MAJOR == 1 && LIBZIP_VERSION_MINOR == 3 && LIBZIP_VERSION_MICRO == 1
                                                               ^
/tmp/pear/temp/zip/php73/php_zip.c: In function 'c_ziparchive_close':
/tmp/pear/temp/zip/php73/php_zip.c:1545:63: error: invalid suffix "a" on integer constant
 #if LIBZIP_VERSION_MAJOR == 1 && LIBZIP_VERSION_MINOR == 3 && LIBZIP_VERSION_MICRO == 1
                                                               ^
make: *** [php73/php_zip.lo] Error 1
ERROR: `make' failed
```

I use the pecl to install it, but failed.

**Comment by remicollet** [comment] 2019-01-30 16:55
Which libzip version are you running ?

**Comment by kasuganosoras** [comment] 2019-01-31 13:50
Libzip 1.5.1

**Comment by kasuganosoras** [comment] 2019-01-31 13:59
I try to comment the code in `php73/php_zip.c`
```C
#if LIBZIP_VERSION_MAJOR == 1 && LIBZIP_VERSION_MINOR == 3 && LIBZIP_VERSION_MICRO == 1
                      php_error_docref(NULL, E_WARNING, "Cannot destroy the zip context: zip_close have failed");
#else
                        php_error_docref(NULL, E_WARNING, "Cannot destroy the zip context: %s", zip_strerror(intern->za));
                        zip_discard(intern->za);
#endif
```
![img](https://i.natfrp.org/1d747c923a9e428d43ea1937d6a41405.png)

And now it can compile successful.
But I don't know what will happen xD

**Comment by kkuhrman** [comment] 2019-03-15 19:59
I have run into same issue. Built libzip 1.5.2 from source with cmake 3.14 and installed to /usr/local/lib64 (target CentOS x86_64). I get the same error on attempt to invoke make whether I try to link statically when building PHP-7.3.2 branch, for example:
`./config.nice (--enable_zip` --with_libzip=/usr/local) 
or as a shared object (zip-1.15.4)

**Comment by kkuhrman** [comment] 2019-03-18 15:15
This is clearly a bug in the libzip library or configuration code. @see https://bugs.php.net/bug.php?id=77150

The problem is in the file zipconf.h with the macro
`#define LIBZIP_VERSION_MICRO 2a`

Removing the 'a' suffix from the above allows the build to proceed but with unpredictable results as noted above by kasuganosoras

**Comment by pierrejoye** [comment] 2019-03-18 15:49
Some (pre) compilers require quotes for string constants, other not. Having
them work on all.

**Comment by remicollet** [comment] 2019-03-19 10:39
> Libzip 1.5.1
> clone from https://github.com/nih-at/libzip

This is not the 1.5.1 version.
checkout the tag to use it

> I have run into same issue. Built libzip 1.5.2 from source with cmake 3.14 and installed to /usr/local/lib64 

Use "remi" repository, which have it (libzip5, php-pec-zip, php 7.1, 7.2, 7.3...)  ;)

**Comment by muarachmann** [comment] 2021-04-08 12:47
I ran into this issue while installing 7.3 for some project which depends on zip ext. Is there a current fix for this?

**Comment by remicollet** [comment] 2021-10-06 13:33
LIBZIP_VERSION_MICRO usage have been removed for some time already

**Closed by remicollet** 2021-10-06 13:33 UTC
