### ISSUE TITLE
error: unknown type name 'zend_literal' when trying to build zip 1.12.1 via PECL

### ISSUE THREAD

**Issue by jgraham909** [pierrejoye/php_zip#2] opened 2013-06-18 17:52 UTC
I have a few issues with UTF-8 encodings and was attempting to use the latest beta as I see several UTF-8 issues were addressed in 1.11.0. However, I am receiving `error: unknown type name 'zend_literal' ` I'm a bit confused from this as it looks like that is defined in zend_compile.h (/usr/include/php5/Zend/zend_compile.h) and /usr/include/php5/Zend is in my include path.

I also receive the same errors if I attempt to compile 1.11.0, or 1.12.0. This error also persists when downloading the package manually and trying phpize. ./configure, make.

Any help would be greatly appreciated. 

The full command and output is below.
<pre>
jeff:~/zip-1.12.1$ sudo pecl config-set preferred_state beta && sudo pecl install zip-1.12.1; sudo pecl config-set preferred_state stable
config-set succeeded
downloading zip-1.12.1.tgz ...
Starting to download zip-1.12.1.tgz (264,431 bytes)
......................................................done: 264,431 bytes
93 source files, building
running: phpize
Configuring for:
PHP Api Version:         20090626
Zend Module Api No:      20090626
Zend Extension Api No:   220090626
building in /tmp/pear/temp/pear-build-rooto8IbRI/zip-1.12.1
running: /tmp/pear/temp/zip/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20090626
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for zip archive read/writesupport... yes, shared
checking for the location of libz... no
checking pcre install prefix... no
checking for the location of zlib... /usr
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for ssize_t... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of off_t... 8
checking size of size_t... 8
checking for touch... /usr/bin/touch
checking for unzip... /usr/bin/unzip
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) nawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/temp/pear-build-rooto8IbRI/zip-1.12.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/zip -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rooto8IbRI/zip-1.12.1/include -I/tmp/pear/temp/pear-build-rooto8IbRI/zip-1.12.1/main -I/tmp/pear/temp/zip -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/zip/php_zip.c -o php_zip.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/zip -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rooto8IbRI/zip-1.12.1/include -I/tmp/pear/temp/pear-build-rooto8IbRI/zip-1.12.1/main -I/tmp/pear/temp/zip -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/zip/php_zip.c  -fPIC -DPIC -o .libs/php_zip.o
/tmp/pear/temp/zip/php_zip.c:849:1: error: unknown type name 'zend_literal'
/tmp/pear/temp/zip/php_zip.c: In function 'php_zip_get_property_ptr_ptr':
/tmp/pear/temp/zip/php_zip.c:872:95: error: request for member 'hash_value' in something not a structure or union
/tmp/pear/temp/zip/php_zip.c:881:3: error: too many arguments to function 'std_hnd->get_property_ptr_ptr'
/tmp/pear/temp/zip/php_zip.c: At top level:
/tmp/pear/temp/zip/php_zip.c:891:1: error: unknown type name 'zend_literal'
/tmp/pear/temp/zip/php_zip.c: In function 'php_zip_read_property':
/tmp/pear/temp/zip/php_zip.c:913:95: error: request for member 'hash_value' in something not a structure or union
/tmp/pear/temp/zip/php_zip.c:929:3: error: too many arguments to function 'std_hnd->read_property'
/tmp/pear/temp/zip/php_zip.c: At top level:
/tmp/pear/temp/zip/php_zip.c:939:1: error: unknown type name 'zend_literal'
/tmp/pear/temp/zip/php_zip.c: In function 'php_zip_has_property':
/tmp/pear/temp/zip/php_zip.c:960:95: error: request for member 'hash_value' in something not a structure or union
/tmp/pear/temp/zip/php_zip.c:985:3: error: too many arguments to function 'std_hnd->has_property'
/tmp/pear/temp/zip/php_zip.c: In function 'zm_startup_zip':
/tmp/pear/temp/zip/php_zip.c:2801:43: warning: assignment from incompatible pointer type [enabled by default]
/tmp/pear/temp/zip/php_zip.c:2804:36: warning: assignment from incompatible pointer type [enabled by default]
/tmp/pear/temp/zip/php_zip.c:2805:35: warning: assignment from incompatible pointer type [enabled by default]
make: *** [php_zip.lo] Error 1
ERROR: `make' failed
config-set succeeded
jeff:~/zip-1.12.1$
</pre>

**Comment by remicollet** [comment] 2015-05-07 12:31
Just give it a try on RHEL-6 with php-5.3.3, zip 1.12.5
Can't reproduce.

@jgraham909 is this issue still present ?

**Comment by remicollet** [comment] 2015-06-11 13:58
No feedback, so Closing

**Closed by remicollet** 2015-06-11 13:58 UTC
